adapter_name = /dev/dri/renderD128
address_family = both
audio_sink = alsa_input._sys_devices_platform_hdmiin-sound_sound_card0.stereo-fallback
capture = v4l2
encoder = rkmpp
gamepad = switch
udc_name = fc000000.usb
keyboard = disabled
min_log_level = 2
mouse = disabled
output_name = 20
wan_encryption_mode = 0
