FFMPEG_CBS_VERSION = $(FFMPEG_SUNSHINE_VERSION)
FFMPEG_CBS_SITE = $(FFMPEG_CBS_PKGDIR)
FFMPEG_CBS_SITE_METHOD = local
FFMPEG_CBS_INSTALL_STAGING = YES
FFMPEG_CBS_INSTALL_TARGET = NO
FFMPEG_CBS_DEPENDENCIES = ffmpeg-sunshine

FFMPEG_CBS_CONF_OPTS += -DFFMPEG_GENERATED_SRC_PATH=$(FFMPEG_SUNSHINE_SRCDIR)
FFMPEG_CBS_CONF_OPTS += -DCMAKE_INSTALL_PREFIX=/opt/ffmpeg-sunshine

$(eval $(cmake-package))
